### ISSUE TITLE
Research APIs for backend (Stock)

### ISSUE THREAD

**Issue by vijayxtreme** [team-hack/stockapp#7]
Look at free APIs, open source, crypto

**Comment by jamesnewking** [comment]
This is a great article on the different stock API's available: [Medium](https://medium.com/@patrick.collins_58673/stock-api-landscape-5c6e054ee631)

I will go through each one to understand the pro/cons.

**Comment by jamesnewking** [comment]
Let's go with https://www.alphavantage.co/
Because it's easy to get an API key and it's free for what we need.
```
We are pleased to provide free stock API service for our global community of users for up to 5 API requests per minute and 500 requests per day. 
```

1st endpoint we need is a search function. To determine a valid stock ticker name. Here's an example of their API and output in JSON:
https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=BA&apikey=demo

**Comment by jamesnewking** [comment]
This is a interesting series of videos on creating a React Stock APP from scratch. But the difference is this project is all front-end. There is no backend since they are calling the 3rd party stock API directly and formatting on the front-end. We should still create our own backend and format the data to how we want it.
[https://www.youtube.com/watch?v=onSKOD3RPo8&list=PLjItgYqIzJ9VOBgwZ82D9kjQ_QtM5R4u5](https://www.youtube.com/watch?v=onSKOD3RPo8&list=PLjItgYqIzJ9VOBgwZ82D9kjQ_QtM5R4u5)

[eToro](https://www.etoro.com/) is an interesting social stock app.

**Comment by vijayxtreme** [comment]
James looking awesome! I think this is a good one to start with so we'll try working with this API

**Comment by vijayxtreme** [comment]
Closing this issue, seems a bit stale.  If we need to do more research, please open a new issue.
